[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
soliot_smart_contract = "EKkpJJaunXrdfiui5qn7eztjiYHqkXLpxBjxst8qrpyU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ritikbhatt020/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
